### ISSUE TITLE
add pictures

### ISSUE THREAD

**Issue by llau-kicker** [Austix6E/KMSwitch#1]
add pictures

**Comment by Austix6E** [comment]
![PXL_20240921_053710393](https://github.com/user-attachments/assets/c5805ce4-f90e-4845-9a99-89e47f317b6c)

basic idea is to be able to switch a keyboard and mouse between my work and personal comp while also having the option to direct pass through the k/m to one of the PCs for gaming and extra mouse functionality (like logitech G HUB) 

Haven't got around to finishing the software yet but if I remember correctly I have the pass through and the k/m master working individually.

**Comment by llau-kicker** [comment]
I fully did not expect to get an actual picture 😂
sounds like a neat tool!
